### ISSUE TITLE
Frontend Page Checklist

### ISSUE THREAD

**Issue by qixils** [qixils/kgdq#20]
~~todo: list relevant api endpoints~~

- [x] Page Template `/+layout.svelte`
  - Navbar
    - ~~Links to organization homepages, maybe with a dropdown for events by those organizations?~~
    - discord login button
  - Footer
    - Copyright notice, links to this repo
- [x] Homepage `/`
  - Describes the site
  - Idk what else to put here yet. gdqvods has a list of featured runs which sounds cool but sounds like a v1.1 thing not a v1.0 thing.
- [x] Organization homepage `/event/[org]/`
  - Lists all the organization's events and when they are/were, maybe total money raised?
- [x] Event schedule `/event/[org]/[slug]/`
  - [x] Still todo: button for logged in users to suggest VOD links (bring up a short popup text box modal?)
- [x] Admin panel `/admin/`
  - For approving suggested VOD links

**Comment by dunkyl** [comment]
- [ ] Consistent "loading!!!" style
- [ ] Remove `'user'` from `localStorage` when cookie expires (1 week currently) (does not have to be addressed until like june 3rd)
